### PR TITLE
Migrate to docker

### PR DESCRIPTION
**Pull request by minamorl**
## What

I added Dockerfiles and some things.
## Why

To share the environment with the developers. Now we can easily set up development environment with only `docker-compose` commands.
## Notes

This patch supports webpack-dev-server. `docker-compsose up` is an alternative to `npm start`. Docker containers automatically sync under /ui folder. So we won't lose watching feature.

### CODE REVIEW

**Comment by seanchas116** [comment]
Great changes 👍  but I encountered node-sass installation error on my Mac:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN respass@1.0.0 No repository field.
npm ERR! Linux 4.4.12-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /respass/npm-debug.log
```

**Comment by seanchas116** [comment]
More logs:

```
> node-sass@3.8.0 install /respass/node_modules/node-sass
> node scripts/install.js

/respass/node_modules/asn1/lib/ber/reader.js:48
/**
^^^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/respass/node_modules/asn1/lib/ber/index.js:6:14)
    at Module._compile (module.js:541:32)
```

**Comment by minamorl** [comment]
Hmm... seems odd. Could you try `rm -rf node_modules` on your repo and give me a result of `docker-compose run --entrypoint docker/init.sh respass`? Docker image shares `node_modules` under your repo to reuse. This may cause error.

**Comment by seanchas116** [comment]
> I encountered node-sass installation error on my Mac:

Sorry, I managed to fix this by deleting `node_module` and rerunning `docker-compose run --entrypoint docker/test.sh respass` (looks like some files in `node_modules` were corrupt somehow)

**Comment by seanchas116** [comment]
Now `docker-compsose up` works fine in my environment ✨ 

image

**Comment by seanchas116** [comment]
I encountered another problem: I run tests by `docker-compose run --entrypoint docker/test.sh respass` but some of them fail:

```
  1) wsserver without auth must not emit join event if anonymous user joins:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true

      at Decorator._callFunc (node_modules/empower-core/lib/decorator.js:110:20)
      at Decorator.concreteAssert (node_modules/empower-core/lib/decorator.js:103:17)
      at Function.decoratedAssert [as equal] (node_modules/empower-core/lib/decorate.js:51:30)
      at WebSocket.ws1.on (lib/test/test_wsserver.js:105:24)
      at WebSocket.cleanupWebsocketResources (node_modules/ws/lib/WebSocket.js:950:8)
      at endReadableNT (_stream_readable.js:973:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) wsserver without auth must not emit left event if anonymous user leaves:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true

      at Decorator._callFunc (node_modules/empower-core/lib/decorator.js:110:20)
      at Decorator.concreteAssert (node_modules/empower-core/lib/decorator.js:103:17)
      at Function.decoratedAssert [as equal] (node_modules/empower-core/lib/decorate.js:51:30)
      at WebSocket.ws2.on (lib/test/test_wsserver.js:122:24)
      at WebSocket.cleanupWebsocketResources (node_modules/ws/lib/WebSocket.js:950:8)
      at endReadableNT (_stream_readable.js:973:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by seanchas116** [comment]
oh it was because `SUPPORT_ANONYMOUS_USER` is set to true in my `.env`.

**Comment by seanchas116** [comment]
I set `SUPPORT_ANONYMOUS_USER` to false and all tests passed.

**Comment by seanchas116** [comment]
Now looks good 😄

**Pull request merged**
